name: EAS Build & Deploy

on:
  push:
    branches:
      - azure-branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # Login via variável de ambiente

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar EAS CLI
        run: npm install -g eas-cli

      - name: Login no Expo
        run: eas login --token $EXPO_TOKEN

      - name: Build APK Android (produção)
        run: eas build --platform android --profile production --non-interactive --output-format apk

      # Se quiser submeter para a loja automaticamente, descomente abaixo:
      # - name: Submeter app para a loja Google Play
      #   run: eas submit --platform android --profile production --non-interactive
