name: EAS Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar EAS CLI
        run: npm install -g eas-cli

      - name: Login no Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build para Android e iOS (produção)
        run: eas build --platform all --profile production --non-interactive

      # Se quiser submeter para a loja automaticamente, descomente abaixo:
      # - name: Submeter app para as lojas
      #   run: eas submit --platform all --profile production --non-interactive
